In [1]:
%matplotlib notebook
from QDP import qdp
import os.path
import numpy as np
from scipy.stats import poisson
import h5py
import matplotlib.pyplot as plt
from scipy.optimize import leastsq,curve_fit

In [2]:
#analysis_master_path='Y:/Rb/Analysis/' # Y:\ is network drive connected to Hexagon E:\Rb\

exp_id='2018_02_06_15_02_40_Microwave RFE'
data_master_path='D:/Data/' # D:\ is local SSD in the main experiment computer
exp_date="_".join(exp_id.split("_")[:3]) # Date folder name automatically generated from exp name.
exp_path=data_master_path+exp_date+'/'+exp_id+'/'
experiment_file='results.hdf5'
dp=exp_path
cuts = [[450],[450],[450]]

q = qdp.QDP(base_data_path=dp)
q.load_data_file(experiment_file)
for r in range(5):
    q.set_thresholds(cuts, roi=r)

C:\Users\Rb\AppData\Local\Enthought\Canopy\User\lib\site-packages\numpy\core\fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\Rb\AppData\Local\Enthought\Canopy\User\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [3]:
print q.experiments[0]['variable_list']
xlab = q.experiments[0]['variable_desc'][q.experiments[0]['variable_list'][0]]['description']
print xlab

[u't_microwave']
microwave duration (ms)


In [4]:
retention = q.apply_thresholds()
print q.get_retention()['retention']
print retention['ivar']


[[[ 0.          0.          0.          0.          0.        ]
  [ 0.09333333  0.05095541  0.07042254  0.09090909  0.11764706]
  [ 0.25        0.23863636  0.22535211  0.5         0.22727273]
  [ 0.46590909  0.47794118  0.55714286  0.4         0.46666667]
  [ 0.5915493   0.7443609   0.82857143  0.54545455  0.72727273]
  [ 0.65625     0.8372093   0.87142857  0.91666667  0.72222222]
  [ 0.70652174  0.81609195  0.87142857  0.69565217  0.65      ]
  [ 0.5212766   0.58381503  0.74285714  0.65217391  0.36      ]
  [ 0.31764706  0.375       0.34285714  0.39130435  0.17647059]
  [ 0.10989011  0.15384615  0.14285714  0.18518519  0.21428571]
  [ 0.          0.0390625   0.          0.          0.09090909]
  [ 0.03797468  0.06060606  0.05714286  0.0952381   0.        ]
  [ 0.16049383  0.25824176  0.28169014  0.22222222  0.2       ]
  [ 0.44736842  0.53061224  0.42857143  0.6         0.5       ]
  [ 0.55405405  0.61654135  0.74285714  0.8125      0.75      ]
  [ 0.6025641   0.79881657  0.85714286  

In [15]:
print q.get_retention()

{'loading': array([[[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.05,  0.05,  0.05,  0.05,  0.05],
        [ 0.1 ,  0.1 ,  0.1 ,  0.1 ,  0.1 ],
        [ 0.15,  0.15,  0.15,  0.15,  0.15],
        [ 0.2 ,  0.2 ,  0.2 ,  0.2 ,  0.2 ],
        [ 0.25,  0.25,  0.25,  0.25,  0.25],
        [ 0.3 ,  0.3 ,  0.3 ,  0.3 ,  0.3 ],
        [ 0.35,  0.35,  0.35,  0.35,  0.35],
        [ 0.4 ,  0.4 ,  0.4 ,  0.4 ,  0.4 ],
        [ 0.45,  0.45,  0.45,  0.45,  0.45],
        [ 0.5 ,  0.5 ,  0.5 ,  0.5 ,  0.5 ],
        [ 0.55,  0.55,  0.55,  0.55,  0.55],
        [ 0.6 ,  0.6 ,  0.6 ,  0.6 ,  0.6 ],
        [ 0.65,  0.65,  0.65,  0.65,  0.65],
        [ 0.7 ,  0.7 ,  0.7 ,  0.7 ,  0.7 ],
        [ 0.75,  0.75,  0.75,  0.75,  0.75],
        [ 0.8 ,  0.8 ,  0.8 ,  0.8 ,  0.8 ],
        [ 0.85,  0.85,  0.85,  0.85,  0.85],
        [ 0.9 ,  0.9 ,  0.9 ,  0.9 ,  0.9 ],
        [ 0.95,  0.95,  0.95,  0.95,  0.95],
        [ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ]]]), 'ivar': array([[[ 0.  ,  0.  ,  0.  ,  0

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
[[[ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]
  [ nan  nan  nan  nan  nan]]]
